  sudo: required
  language: python
  os:
    - linux
  cache: pip
  python:
    - 3.6
  services:
    - redis-server
    - docker
  install:
    - pip install -r requirements.txt
    - pip install codecov
    - pip install -e .[test]
  script:
    - pytest
    - docker build -t smomni/seppuku-api .
    - docker run smomni/seppuku-api
  after_script:
    - codecov
    - docker images